version: "3.0"

services:
  go-app:
    stdin_open: true      # docker run -i
    tty: true             # docker run -t
    build: ./docker/
    ports: 
      - "8888:8888"
    volumes:
      - ./:/go/app
    entrypoint: /bin/bash
